# Generated by Django 4.0 on 2022-01-04 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registered_users',
            options={'verbose_name': 'Registered Users'},
        ),
        migrations.RenameField(
            model_name='registered_users',
            old_name='nationality',
            new_name='country',
        ),
        migrations.AddField(
            model_name='registered_users',
            name='address',
            field=models.TextField(default='xyz', max_length=200),
        ),
        migrations.AddField(
            model_name='registered_users',
            name='pincode',
            field=models.IntegerField(default=110093, max_length=6),
        ),
        migrations.AlterField(
            model_name='registered_users',
            name='author',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
