# Generated by Django 4.0 on 2022-01-05 08:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0003_alter_registered_users_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('expiration_time', models.DateTimeField(default=datetime.datetime(2022, 1, 5, 8, 38, 24, 502174))),
                ('registered_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_form.registered_users')),
            ],
        ),
    ]
