# Generated by Django 4.0 on 2022-01-05 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0004_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 8, 38, 44, 428285)),
        ),
    ]
