# Generated by Django 4.0 on 2022-01-06 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0008_alter_user_otp_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_users',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=6),
        ),
        migrations.AddField(
            model_name='registered_users',
            name='c_email',
            field=models.EmailField(default='xyz@gmail.com', max_length=254, verbose_name='Confirm Email'),
        ),
        migrations.AddField(
            model_name='registered_users',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='registered_users',
            name='address',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registered_users',
            name='country',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='user_otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 5, 54, 52, 427719)),
        ),
    ]
