# Generated by Django 4.0 on 2022-01-06 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0009_registered_users_gender_registered_users_c_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_users',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='registered_users',
            name='c_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Confirm Email'),
        ),
        migrations.AlterField(
            model_name='user_otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 5, 55, 31, 703835)),
        ),
    ]
