# Generated by Django 4.0 on 2022-01-06 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0010_alter_registered_users_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_users',
            name='dob',
            field=models.CharField(help_text='(yyyy-mm-dd)', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 6, 23, 14, 783656)),
        ),
    ]
