# Generated by Django 4.0 on 2022-01-06 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0012_registered_users_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 7, 43, 11, 467962)),
        ),
    ]
