# Generated by Django 4.0 on 2022-01-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0013_alter_user_otp_expiration_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_otp',
            name='expiration_time',
        ),
    ]
