# Generated by Django 4.0 on 2022-01-07 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0014_remove_user_otp_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 8, 4, 35, 487073)),
        ),
    ]
