# Generated by Django 4.0 on 2022-01-07 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0015_user_otp_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_otp',
            name='current_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 8, 1, 19, 338506)),
        ),
        migrations.AlterField(
            model_name='user_otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 8, 6, 19, 338540)),
        ),
    ]
