# Generated by Django 4.0 on 2022-01-07 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0016_user_otp_current_time_alter_user_otp_expiration_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_otp',
            name='current_time',
        ),
        migrations.RemoveField(
            model_name='user_otp',
            name='expiration_time',
        ),
        migrations.AddField(
            model_name='user_otp',
            name='otp_expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 8, 7, 32, 95002)),
        ),
        migrations.AddField(
            model_name='user_otp',
            name='otp_generate_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 8, 2, 32, 94968)),
        ),
    ]
