# Generated by Django 4.0 on 2022-01-10 08:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0020_alter_user_otp_otp_expiration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_users',
            name='address',
            field=models.TextField(default='xyz', max_length=200),
        ),
        migrations.AlterField(
            model_name='registered_users',
            name='password',
            field=models.CharField(default='Hash@123', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_otp',
            name='otp_expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 8, 22, 44, 473401, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_otp',
            name='otp_generate_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 8, 17, 44, 473359, tzinfo=utc)),
        ),
    ]
