# Generated by Django 4.0 on 2022-01-10 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_form', '0022_alter_user_otp_otp_expiration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_otp',
            name='otp_expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 8, 45, 42, 919276, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_otp',
            name='otp_generate_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 8, 43, 42, 919235, tzinfo=utc)),
        ),
    ]
